# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84db9042d3ac0bfb46588b9c81926187764c49696ff8c009f122e1c8419ab6a55bd3667c0613bd9dcd66fb7b794621e7db57fdfd30047a9751b0b8c80792e724

test:
  secret_key_base: e28ec8ac840af6521bbaec089d4b411e8b7643c3ad90bf25d748268603d4daba98909379028c8430f351973e985a951cef0e14baa0187bda857a1babb5c925c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
